### ISSUE TITLE
GameCrash MC 1.18.2 with Forge 40.1.21

### ISSUE THREAD

**Issue by DancerVlt69** [Autovw/MoreConcrete#2]
If I start MC with your mod version 1.4.0 for MC 1.18.2 with Forge 40.1.21 in multi play I get the following crash report:
`---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 21.05.22, 20:38
Description: Getting block state

net.minecraft.world.level.chunk.MissingPaletteEntryException: Missing Palette entry for index 49826.
	at net.minecraft.world.level.chunk.GlobalPalette.m_5795_(GlobalPalette.java:36) ~[client-1.18.2-20220404.173914-srg.jar%2392!/:?] {re:classloading}
	at net.minecraft.world.level.chunk.PalettedContainer.m_63085_(PalettedContainer.java:132) ~[client-1.18.2-20220404.173914-srg.jar%2392!/:?] {re:classloading}
	at net.minecraft.world.level.chunk.PalettedContainer.m_63087_(PalettedContainer.java:127) ~[client-1.18.2-20220404.173914-srg.jar%2392!/:?] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunkSection.m_62982_(LevelChunkSection.java:52) ~[client-1.18.2-20220404.173914-srg.jar%2392!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.world.level.chunk.LevelChunk.m_8055_(LevelChunk.java:168) ~[client-1.18.2-20220404.173914-srg.jar%2392!/:?] {re:mixin,xf:fml:xaeroworldmap:xaero_wm_chunkclass,re:computing_frames,xf:fml:xaeroworldmap:xaero_wm_chunkclass,re:classloading,xf:fml:xaeroworldmap:xaero_wm_chunkclass,pl:mixin:APP:flywheel.mixins.json:InstanceAddMixin,pl:mixin:A}
	at net.optifine.override.ChunkCacheOF.loadBlockStates(ChunkCacheOF.java:175) ~[OptiFine_1.18.2_HD_U_H7_MOD.jar%2397!/:?] {re:classloading}
	at net.optifine.override.ChunkCacheOF.renderStart(ChunkCacheOF.java:148) ~[OptiFine_1.18.2_HD_U_H7_MOD.jar%2397!/:?] {re:classloading}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$RenderChunk$RebuildTask.m_112865_(ChunkRenderDispatcher.java:983) ~[client-1.18.2-20220404.173914-srg.jar%2392!/:?] {re:mixin,xf:OptiFine:default,re:classloading,xf:OptiFine:default,pl:mixin:APP:flywheel.mixins.json:ChunkRebuildHooksMixin,pl:mixin:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$RenderChunk$RebuildTask.m_5869_(ChunkRenderDispatcher.java:924) ~[client-1.18.2-20220404.173914-srg.jar%2392!/:?] {re:mixin,xf:OptiFine:default,re:classloading,xf:OptiFine:default,pl:mixin:APP:flywheel.mixins.json:ChunkRebuildHooksMixin,pl:mixin:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.lambda$runTask$0(ChunkRenderDispatcher.java:195) ~[client-1.18.2-20220404.173914-srg.jar%2392!/:?] {re:classloading,xf:OptiFine:default}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.world.level.chunk.GlobalPalette.m_5795_(GlobalPalette.java:36) ~[client-1.18.2-20220404.173914-srg.jar%2392!/:?] {re:classloading}
	at net.minecraft.world.level.chunk.PalettedContainer.m_63085_(PalettedContainer.java:132) ~[client-1.18.2-20220404.173914-srg.jar%2392!/:?] {re:classloading}
	at net.minecraft.world.level.chunk.PalettedContainer.m_63087_(PalettedContainer.java:127) ~[client-1.18.2-20220404.173914-srg.jar%2392!/:?] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunkSection.m_62982_(LevelChunkSection.java:52) ~[client-1.18.2-20220404.173914-srg.jar%2392!/:?] {re:classloading,xf:OptiFine:default}
-- Block being got --
Details:
	Location: World: (298,22,-240), Section: (at 10,6,0 in 18,1,-15; chunk contains blocks 288,-64,-240 to 303,319,-225), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
Stacktrace:
	at net.minecraft.world.level.chunk.LevelChunk.m_8055_(LevelChunk.java:168) ~[client-1.18.2-20220404.173914-srg.jar%2392!/:?] {re:mixin,xf:fml:xaeroworldmap:xaero_wm_chunkclass,re:computing_frames,xf:fml:xaeroworldmap:xaero_wm_chunkclass,re:classloading,xf:fml:xaeroworldmap:xaero_wm_chunkclass,pl:mixin:APP:flywheel.mixins.json:InstanceAddMixin,pl:mixin:A}
	at net.optifine.override.ChunkCacheOF.loadBlockStates(ChunkCacheOF.java:175) ~[OptiFine_1.18.2_HD_U_H7_MOD.jar%2397!/:?] {re:classloading}
	at net.optifine.override.ChunkCacheOF.renderStart(ChunkCacheOF.java:148) ~[OptiFine_1.18.2_HD_U_H7_MOD.jar%2397!/:?] {re:classloading}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$RenderChunk$RebuildTask.m_112865_(ChunkRenderDispatcher.java:983) ~[client-1.18.2-20220404.173914-srg.jar%2392!/:?] {re:mixin,xf:OptiFine:default,re:classloading,xf:OptiFine:default,pl:mixin:APP:flywheel.mixins.json:ChunkRebuildHooksMixin,pl:mixin:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$RenderChunk$RebuildTask.m_5869_(ChunkRenderDispatcher.java:924) ~[client-1.18.2-20220404.173914-srg.jar%2392!/:?] {re:mixin,xf:OptiFine:default,re:classloading,xf:OptiFine:default,pl:mixin:APP:flywheel.mixins.json:ChunkRebuildHooksMixin,pl:mixin:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.lambda$runTask$0(ChunkRenderDispatcher.java:195) ~[client-1.18.2-20220404.173914-srg.jar%2392!/:?] {re:classloading,xf:OptiFine:default}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['DancerVlt69'/77172, l='ClientLevel', x=193.78, y=19.50, z=-230.07]]
	Chunk stats: 441, 201
	Level dimension: minecraft:overworld
	Level spawn location: World: (136,75,-250), Section: (at 8,11,6 in 8,4,-16; chunk contains blocks 128,-64,-256 to 143,319,-241), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 141653 game time, 37855516 day time
	Server brand: Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:516) ~[client-1.18.2-20220404.173914-srg.jar%2392!/:?] {re:mixin,xf:OptiFine:default,xf:fml:xaeroworldmap:xaero_wm_clientworldclass,re:computing_frames,xf:OptiFine:default,xf:fml:xaeroworldmap:xaero_wm_clientworldclass,re:classloading,xf:OptiFine:default,xf:fml:xaeroworldmap:xaero_wm_clientworldclass,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:APP:blueprint.mixins.json:client.ClientLevelMixin,pl:mixin:APP:flywheel.mixins.json:ClientLevelMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2255) ~[client-1.18.2-20220404.173914-srg.jar%2392!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.lambda$runTask$2(ChunkRenderDispatcher.java:206) ~[client-1.18.2-20220404.173914-srg.jar%2392!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:653) ~[client-1.18.2-20220404.173914-srg.jar%2392!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%2392!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.20.jar%2316!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Mod Resources, Default, ChromaHills-128x-1.18-v1, Hanging-Baskets-1-1, _PHC2-Pack_private, _UsefulBackpacks, __Test_Pack_0_0_1, xali's+Enchanted+Books+v0.9.zip, Better-Leaves-4.0-§31.16.2+§o.zip

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1360461360 bytes (1297 MiB) / 2919235584 bytes (2784 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: AuthenticAMD
	Processor Name: AMD FX(tm)-8350 Eight-Core Processor           
	Identifier: AuthenticAMD Family 21 Model 2 Stepping 0
	Microarchitecture: Piledriver
	Frequency (GHz): 4,02
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 1050 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095,00
	Graphics card #0 deviceId: 0x1c82
	Graphics card #0 versionInfo: DriverVersion=30.0.15.1123
	Memory slot #0 capacity (MB): 8192,00
	Memory slot #0 clockSpeed (GHz): 0,80
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 8192,00
	Memory slot #1 clockSpeed (GHz): 0,80
	Memory slot #1 type: DDR3
	Virtual memory max (MB): 30677,85
	Virtual memory used (MB): 20093,80
	Swap memory total (MB): 14336,00
	Swap memory used (MB): 480,43
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.18.2-forge-40.1.20
	Backend library: LWJGL version 3.2.2 SNAPSHOT
	Backend API: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 511.23, NVIDIA Corporation
	Window size: 1680x1027
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: mod_resources, vanilla, file/ChromaHills-128x-1.18-v1, file/Hanging-Baskets-1-1, file/_PHC2-Pack_private (incompatible), file/_UsefulBackpacks (incompatible), file/__Test_Pack_0_0_1 (incompatible), file/xali's+Enchanted+Books+v0.9.zip (incompatible), file/Better-Leaves-4.0-§31.16.2+§o.zip (incompatible)
	Current Language: Deutsch (Deutschland)
	CPU: 8x AMD FX(tm)-8350 Eight-Core Processor 
	OptiFine Version: OptiFine_1.18.2_HD_U_H7
	OptiFine Build: 20220410-185216
	Render Distance Chunks: 6
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: ComplementaryShaders_v4.4.zip
	OpenGlVersion: 3.2.0 NVIDIA 511.23
	OpenGlRenderer: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8
	ModLauncher: 9.1.3+9.1.3+main.9b69c82a
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 slf4jfixer PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 OptiFine TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		client-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		FarmersDelight-1.18.2-1.1.1.jar                   |Farmer's Delight              |farmersdelight                |1.18.2-1.1.1        |DONE      |Manifest: NOSIGNATURE
		useful_backpacks-1.18.2-1.12.1.93.jar             |Useful Backpacks              |usefulbackpacks               |1.12.1.93           |DONE      |Manifest: f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		theoneprobe-1.18-5.1.0.jar                        |The One Probe                 |theoneprobe                   |1.18-5.1.0          |DONE      |Manifest: NOSIGNATURE
		TerraBlender-forge-1.18.2-1.1.0.99.jar            |TerraBlender                  |terrablender                  |1.18.2-1.1.0.99     |DONE      |Manifest: NOSIGNATURE
		BiomesOPlenty-1.18.2-16.0.0.111-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.18.2-16.0.0.111   |DONE      |Manifest: NOSIGNATURE
		Jade-1.18.2-5.1.0.jar                             |Jade                          |jade                          |5.1.0               |DONE      |Manifest: NOSIGNATURE
		beenfo-1.18.1-forge39.0.9-1.2.jar                 |Beenfo                        |beenfo                        |1.18.1-forge39.0.9-1|DONE      |Manifest: NOSIGNATURE
		jei-1.18.2-9.7.0.195.jar                          |Just Enough Items             |jei                           |9.7.0.195           |DONE      |Manifest: NOSIGNATURE
		pamhc2foodextended-1.18.2-1.0.0.jar               |Pam's HarvestCraft 2 - Food Ex|pamhc2foodextended            |1.0                 |DONE      |Manifest: NOSIGNATURE
		bambooeverything-1.2.6-build.13+mc1.18.2.jar      |Bamboo Everything             |bambooeverything              |1.2.6-build.13+mc1.1|DONE      |Manifest: NOSIGNATURE
		flywheel-forge-1.18-0.6.2.jar                     |Flywheel                      |flywheel                      |1.18-0.6.2          |DONE      |Manifest: NOSIGNATURE
		pamhc2foodcore-1.18.2-1.0.1.jar                   |Pam's HarvestCraft 2 - Food Co|pamhc2foodcore                |1.0.1               |DONE      |Manifest: NOSIGNATURE
		gravestone-1.18.2-1.0.2.jar                       |Gravestone Mod                |gravestone                    |1.18.2-1.0.2        |DONE      |Manifest: NOSIGNATURE
		moreconcrete-1.4.0-1.18.2.jar                     |More Concrete                 |moreconcrete                  |1.4.0               |DONE      |Manifest: NOSIGNATURE
		Xaeros_WorldMap_1.22.0_Forge_1.18.2.jar           |Xaero's World Map             |xaeroworldmap                 |1.22.0              |DONE      |Manifest: NOSIGNATURE
		Cooking4blockheads-forge-1.18.2-12.0.0.jar        |CookingForBlockheads          |cookingforblockheads          |12.0.0              |DONE      |Manifest: NOSIGNATURE
		Placebo-1.18.2-6.4.0.jar                          |Placebo                       |placebo                       |6.4.0               |DONE      |Manifest: NOSIGNATURE
		StorageDrawers-1.18.2-10.2.0.jar                  |Storage Drawers               |storagedrawers                |10.2.0              |DONE      |Manifest: NOSIGNATURE
		Twitchspawn_1.18.2-1.9.3.jar                      |TwitchSpawn                   |twitchspawn                   |1.9.3               |DONE      |Manifest: NOSIGNATURE
		Serene+Seasons-1.18.2-7.0.0.13.jar                |Serene Seasons                |sereneseasons                 |1.18.2-7.0.0.13     |DONE      |Manifest: NOSIGNATURE
		configured-1.5.3-1.18.2.jar                       |Configured                    |configured                    |1.5.3               |DONE      |Manifest: NOSIGNATURE
		libnonymous-2.1.0.jar                             |libnonymous                   |libnonymous                   |2.1.0               |DONE      |Manifest: NOSIGNATURE
		Decorative+Blocks-forge-1.18.2-2.1.0.jar          |Decorative Blocks             |decorative_blocks             |2.1.0               |DONE      |Manifest: NOSIGNATURE
		InventoryHud_[1.18].forge-3.4.4.jar               |Inventory HUD+(Forge edition) |inventoryhud                  |3.4.4               |DONE      |Manifest: NOSIGNATURE
		Farming4Blockheads-forge-1.18.2-10.0.1.jar        |Farming for Blockheads        |farmingforblockheads          |10.0.1              |DONE      |Manifest: NOSIGNATURE
		Bookshelf-Forge-1.18.2-13.0.13.jar                |Bookshelf                     |bookshelf                     |13.0.13             |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		u_team_core-1.18.2-4.0.0.204.jar                  |U Team Core                   |uteamcore                     |4.0.0.204           |DONE      |Manifest: f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		Apotheosis-1.18.2-5.3.5.jar                       |Apotheosis                    |apotheosis                    |5.3.5               |DONE      |Manifest: NOSIGNATURE
		architectury-4.4.60.jar                           |Architectury                  |architectury                  |4.4.60              |DONE      |Manifest: NOSIGNATURE
		ftb-library-forge-1802.3.6-build.119.jar          |FTB Library                   |ftblibrary                    |1802.3.6-build.119  |DONE      |Manifest: NOSIGNATURE
		JMSR_Forge-1.18.2-0.1.8a.jar                      |JMSR for Forge                |jmsr_forge                    |1.18.2-0.1.8a       |DONE      |Manifest: NOSIGNATURE
		catalogue-1.6.1-1.18.2.jar                        |Catalogue                     |catalogue                     |1.6.1               |DONE      |Manifest: NOSIGNATURE
		balm-3.0.3+0.jar                                  |Balm                          |balm                          |3.0.3+0             |DONE      |Manifest: NOSIGNATURE
		JEITweaker-1.18.2-3.0.0.8.jar                     |JEI Tweaker                   |jeitweaker                    |3.0.0.8             |DONE      |Manifest: NOSIGNATURE
		blueprint-1.18.2-5.3.2.jar                        |Blueprint                     |blueprint                     |5.3.2               |DONE      |Manifest: NOSIGNATURE
		savage_and_ravage-1.18.2-4.0.0.jar                |Savage & Ravage               |savage_and_ravage             |4.0.0               |DONE      |Manifest: NOSIGNATURE
		CraftTweaker-forge-1.18.2-9.1.140.jar             |CraftTweaker                  |crafttweaker                  |9.1.140             |DONE      |Manifest: NOSIGNATURE
		beehive-tooltips-forge-1.4.2.jar                  |Beehive Tooltips              |beehivetooltips               |1.4.2               |DONE      |Manifest: NOSIGNATURE
		forge-1.18.2-40.1.20-universal.jar                |Forge                         |forge                         |40.1.20             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
	Flywheel Backend: Off
	Crash Report UUID: ca88ac66-47b8-4841-9d10-a32c6de2f12a
	FML: 40.1
	Forge: net.minecraftforge:40.1.20`

If I deactivate the Xaero-Maps all wil wokr fine if I enter the server. If I play in single play with the same configuration all works fine. 

Do you have any ideas what I can do?

btw: Thanks for the nice work!

DancerVLT69

**Comment by Autovw** [comment]
This crash does not point towards More Concrete, but rather an incompatibility between Xaero's Worldmap and Optifine.

**Comment by DancerVlt69** [comment]
That was also my first suspicion. But if I have had deactivate/remove MoreConcrete all was fine. 

BUT

Last night a newer version of Forge and the Xaeros Minimap was available and - at the moment - it looks like, the problem is solved. 

Nonetheless, thanks for your efforts.
